name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - P0 - Critical (crash/data loss)
        - P1 - High (feature broken, no workaround)
        - P2 - Medium (feature broken, workaround exists)
        - P3 - Low (cosmetic/minor)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Lan Version
      description: Output of `lan --version`
      placeholder: "v0.1.0-beta"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS / Architecture
      placeholder: "macOS 15.3 arm64 / Ubuntu 24.04 x86_64"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Run `lan ...`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs or attach screenshots. Run `./scripts/support-bundle.sh` for diagnostics.
    validations:
      required: false
