name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - CLI / TUI
        - Tool Runtime
        - Skill System
        - Provider / Routing
        - Install / Upgrade / Release
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like it to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Lan Version (if relevant)
      placeholder: "v0.1.0-beta"
    validations:
      required: false
